//注入路由引擎
app.config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	//声明默认导航
	$urlRouterProvider.when('','/index');
	$stateProvider.state('index',{
		url:'/index',
		templateUrl:'view/index.html',
		controller:'indexCtrl'
	}).state('news',{
		url:'/news',
		templateUrl:'view/news.html',
		controller:'newsCtrl'
	}).state('news.top',{
		url:'/top',
		templateUrl:'view/top.html',
		controller:'topCtrl'
	}).state('news.guoji',{
		url:'/guoji',
		templateUrl:'view/guoji.html',
		controller:'guojiCtrl'
	}).state('news.guonei',{
		url:'/guonei',
		templateUrl:'view/guonei.html',
		controller:'guoneiCtrl'
	}).state('news.shehui',{
		url:'/shehui',
		templateUrl:'view/shehui.html',
		controller:'shehuiCtrl'
	}).state('news.yule',{
		url:'/yule',
		templateUrl:'view/yule.html',
		controller:'yuleCtrl'
	}).state('news.tiyu',{
		url:'/tiyu',
		templateUrl:'view/tiyu.html',
		controller:'tiyuCtrl'
	}).state('news.junshi',{
		url:'/junshi',
		templateUrl:'view/junshi.html',
		controller:'junshiCtrl'
	}).state('news.keji',{
		url:'/keji',
		templateUrl:'view/keji.html',
		controller:'kejiCtrl'
	}).state('news.caijing',{
		url:'/caijing',
		templateUrl:'view/caijing.html',
		controller:'caijingCtrl'
	}).state('news.shishang',{
		url:'/shishang',
		templateUrl:'view/shishang.html',
		controller:'shishangCtrl'
	})//这是littleApp
	.state('littleApp',{
		url:'/littleApp',
		templateUrl:'view/littleApp.html',
		controller:'littleAppCtrl'
	}).state('littleApp.oil',{
		url:'/oil',
		templateUrl:'view/oil.html',
		controller:'oilCtrl'
	})
}]);
